package com.cuida.controller;

import com.cuida.entity.*; import com.cuida.repository.*; import com.cuida.service.AcessoService; import com.fasterxml.jackson.core.JsonProcessingException; import com.fasterxml.jackson.databind.ObjectMapper; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
import java.time.*; import java.util.*;

/** Small JSON adapter for the shipped UI contract. Domain persistence stays relational; JSON is used only for variable form payloads. */
@RestController @RequiredArgsConstructor
public class FrontendParityController {
 private final AcessoService acesso; private final RotinaRepository rotinas; private final TipoAfericaoRepository tipos; private final LeituraRepository leituras; private final AlertaRepository alertas; private final CompartilhamentoRepository compartilhamentos; private final com.cuida.repository.NotaRepository notas; private final ObjectMapper json;
 private String text(Object v){try{return json.writeValueAsString(v);}catch(JsonProcessingException e){throw new IllegalArgumentException("Dados inválidos");}}
 private <T> T read(String v,Class<T> c){try{return json.readValue(v,c);}catch(Exception e){throw new IllegalArgumentException("Dados inválidos");}}
 private Map<String,Object> map(Object v){return read(text(v),Map.class);}
 private Map<String,Object> nota(Nota n){Map<String,Object>m=new LinkedHashMap<>();m.put("id",n.getId());m.put("pessoaId",n.getPessoa().getId());m.put("titulo",n.getTitulo());m.put("quando",n.getQuando().toString());m.put("texto",n.getTexto());m.put("status",n.getStatus());m.put("motivoPulo",n.getMotivoPulo());m.put("rotinaId",n.getRotinaId());m.put("tipo",n.getTipo());m.put("criadoEm",n.getCriadoEm()==null?null:n.getCriadoEm().toString());return m;}
 private Map<String,Object> alerta(Alerta x){Map<String,Object>m=new LinkedHashMap<>();m.put("id",x.getId());m.put("patientId",x.getPessoa().getId());m.put("tipo",x.getTipo());m.put("severidade",x.getSeveridade());m.put("titulo",x.getTitulo());m.put("detalhe",x.getDetalhe());m.put("referenciaId",x.getReferenciaId());m.put("criadoEm",x.getCriadoEm()==null?null:x.getCriadoEm().toString());m.put("reconhecidoEm",x.getReconhecidoEm()==null?null:x.getReconhecidoEm().toString());m.put("reconhecidoPor",x.getReconhecidoPor()==null?null:x.getReconhecidoPor().getId());return m;}
 private Map<String,Object> rotina(Rotina r){Map<String,Object> m=new LinkedHashMap<>();m.put("id",r.getId());m.put("patientId",r.getPessoa().getId());m.put("tipo",r.getTipo());m.put("titulo",r.getTitulo());m.put("descricao",r.getDescricao());m.put("horarios",read(r.getHorarios(),List.class));m.put("diasSemana",read(r.getDiasSemana(),List.class));m.put("toleranciaMin",r.getToleranciaMin());m.put("lembreteAntesMin",r.getLembreteAntesMin());m.put("measurementTypeIds",r.getMeasurementTypeIds()==null?null:read(r.getMeasurementTypeIds(),List.class));m.put("medicacao",r.getMedicacao()==null?null:read(r.getMedicacao(),Map.class));m.put("ativo",r.isAtivo());return m;}
 @GetMapping("/api/pessoas/{id}/rotinas") List<Map<String,Object>> listarRotinas(@PathVariable Long id,@RequestParam(defaultValue="false") boolean incluirInativas,Authentication a){Pessoa p=acesso.pessoa(id,a.getName());return rotinas.findByPessoaId(p.getId()).stream().filter(r->incluirInativas||r.isAtivo()).map(this::rotina).toList();}
 @PostMapping("/api/pessoas/{id}/rotinas") @ResponseStatus(HttpStatus.CREATED) Map<String,Object> criarRotina(@PathVariable Long id,@RequestBody Map<String,Object> x,Authentication a){Rotina r=new Rotina();r.setPessoa(acesso.pessoa(id,a.getName()));copy(r,x);return rotina(rotinas.save(r));}
 @PutMapping("/api/pessoas/{id}/rotinas/{rid}") Map<String,Object> atualizarRotina(@PathVariable Long id,@PathVariable Long rid,@RequestBody Map<String,Object> x,Authentication a){Rotina r=rotinas.findByIdAndPessoaId(rid,acesso.pessoa(id,a.getName()).getId()).orElseThrow();copy(r,x);return rotina(rotinas.save(r));}
 @PatchMapping("/api/pessoas/{id}/rotinas/{rid}") Map<String,Object> alternarRotina(@PathVariable Long id,@PathVariable Long rid,@RequestBody Map<String,Object> x,Authentication a){Rotina r=rotinas.findByIdAndPessoaId(rid,acesso.pessoa(id,a.getName()).getId()).orElseThrow();if(x.containsKey("ativo"))r.setAtivo((Boolean)x.get("ativo"));if(x.containsKey("quantidadeAtual")){Map<String,Object> med=r.getMedicacao()==null?new LinkedHashMap<>():read(r.getMedicacao(),Map.class);Map<String,Object> est=med.get("estoque") instanceof Map?new LinkedHashMap<>((Map)med.get("estoque")):new LinkedHashMap<>();est.put("quantidadeAtual",x.get("quantidadeAtual"));med.put("estoque",est);r.setMedicacao(text(med));}return rotina(rotinas.save(r));}
 private void copy(Rotina r,Map<String,Object>x){r.setTipo((String)x.get("tipo"));r.setTitulo((String)x.get("titulo"));r.setDescricao((String)x.get("descricao"));r.setHorarios(text(x.getOrDefault("horarios",List.of())));r.setDiasSemana(text(x.getOrDefault("diasSemana",List.of())));r.setToleranciaMin(((Number)x.getOrDefault("toleranciaMin",30)).intValue());r.setLembreteAntesMin(((Number)x.getOrDefault("lembreteAntesMin",15)).intValue());if(x.get("measurementTypeIds")!=null)r.setMeasurementTypeIds(text(x.get("measurementTypeIds")));if(x.get("medicacao")!=null)r.setMedicacao(text(x.get("medicacao")));}
 @GetMapping("/api/rotinas/{rid}") Map<String,Object> rotina(@PathVariable Long rid,Authentication a){Rotina r=rotinas.findById(rid).orElseThrow();acesso.pessoa(r.getPessoa().getId(),a.getName());return rotina(r);}
 @PutMapping("/api/rotinas/{rid}") Map<String,Object> rotinaAtualizar(@PathVariable Long rid,@RequestBody Map<String,Object>x,Authentication a){Rotina r=rotinas.findById(rid).orElseThrow();acesso.pessoa(r.getPessoa().getId(),a.getName());copy(r,x);return rotina(rotinas.save(r));}
 @PatchMapping("/api/rotinas/{rid}") Map<String,Object> rotinaPatch(@PathVariable Long rid,@RequestBody Map<String,Object>x,Authentication a){Rotina r=rotinas.findById(rid).orElseThrow();acesso.pessoa(r.getPessoa().getId(),a.getName());if(x.containsKey("ativo"))r.setAtivo((Boolean)x.get("ativo"));if(x.containsKey("quantidadeAtual")){Map<String,Object>m=r.getMedicacao()==null?new LinkedHashMap<>():read(r.getMedicacao(),Map.class);Map<String,Object>e=m.get("estoque") instanceof Map?new LinkedHashMap<>((Map)m.get("estoque")):new LinkedHashMap<>();e.put("quantidadeAtual",x.get("quantidadeAtual"));m.put("estoque",e);r.setMedicacao(text(m));}return rotina(rotinas.save(r));}
 @GetMapping("/api/tipos-afericao") List<Map<String,Object>> listarTipos(@RequestParam(defaultValue="false") boolean incluirInativas,Authentication a){Usuario u=acesso.usuario(a.getName());return tipos.findAll().stream().filter(t->t.isSistema()||(t.getUsuario()!=null&&t.getUsuario().getId().equals(u.getId()))).filter(t->incluirInativas||t.isAtivo()).map(t->{Map<String,Object>m=new LinkedHashMap<>();m.put("id",t.getId());m.put("slug",t.getSlug());m.put("nome",t.getNome());m.put("icone",t.getIcone());m.put("campos",read(t.getCampos(),List.class));m.put("alertaSemRegistroHoras",t.getAlertaSemRegistroHoras());m.put("sistema",t.isSistema());m.put("ativo",t.isAtivo());return m;}).toList();}
 @GetMapping("/api/tipos-afericao/{id}") Map<String,Object> obterTipo(@PathVariable Long id,Authentication a){Usuario u=acesso.usuario(a.getName());TipoAfericao t=tipos.findById(id).orElseThrow();permitirTipo(t,u);Map<String,Object>m=new LinkedHashMap<>();m.put("id",t.getId());m.put("slug",t.getSlug());m.put("nome",t.getNome());m.put("icone",t.getIcone());m.put("campos",read(t.getCampos(),List.class));m.put("alertaSemRegistroHoras",t.getAlertaSemRegistroHoras());m.put("sistema",t.isSistema());m.put("ativo",t.isAtivo());return m;}
 @PostMapping("/api/tipos-afericao") @ResponseStatus(HttpStatus.CREATED) Map<String,Object> criarTipo(@RequestBody Map<String,Object>x,Authentication a){TipoAfericao t=new TipoAfericao();t.setSlug((String)x.get("slug"));t.setNome((String)x.get("nome"));t.setIcone((String)x.get("icone"));t.setCampos(text(x.get("campos")));t.setSistema(false);t.setAtivo(true);t.setUsuario(acesso.usuario(a.getName()));return obterTipo(tipos.save(t).getId(),a);}
 @PutMapping("/api/tipos-afericao/{id}") Map<String,Object> atualizarTipo(@PathVariable Long id,@RequestBody Map<String,Object>x,Authentication a){Usuario u=acesso.usuario(a.getName());TipoAfericao t=tipos.findById(id).orElseThrow();permitirTipo(t,u);if(x.get("nome")!=null)t.setNome((String)x.get("nome"));if(x.get("campos")!=null)t.setCampos(text(x.get("campos")));return obterTipo(tipos.save(t).getId(),a);}
 @PatchMapping("/api/tipos-afericao/{id}") void ativoTipo(@PathVariable Long id,@RequestBody Map<String,Object>x,Authentication a){Usuario u=acesso.usuario(a.getName());TipoAfericao t=tipos.findById(id).orElseThrow();permitirTipo(t,u);t.setAtivo((Boolean)x.get("ativo"));tipos.save(t);}
 private void permitirTipo(TipoAfericao t,Usuario u){if(!t.isSistema()&&(t.getUsuario()==null||!t.getUsuario().getId().equals(u.getId())))throw new org.springframework.security.access.AccessDeniedException("Tipo fora do escopo do cuidador");}
 @GetMapping("/api/pessoas/{id}/leituras") List<Map<String,Object>> listarLeituras(@PathVariable Long id,@RequestParam(required=false) Long tipo,@RequestParam(required=false) String campo,Authentication a){acesso.pessoa(id,a.getName());return leituras.findByPessoaIdOrderByAferidoEmDesc(id).stream().filter(r->tipo==null||r.getTipo().getId().equals(tipo)).filter(r->campo==null||r.getCampo().equals(campo)).map(this::leitura).toList();}
 @PostMapping("/api/pessoas/{id}/leituras") @ResponseStatus(HttpStatus.CREATED) Map<String,Object> criarLeitura(@PathVariable Long id,@RequestBody Map<String,Object>x,Authentication a){Pessoa p=acesso.pessoa(id,a.getName());TipoAfericao t=tipos.findById(((Number)x.get("measurementTypeId")).longValue()).orElseThrow();permitirTipo(t,acesso.usuario(a.getName()));Leitura l=Leitura.builder().pessoa(p).tipo(t).nota(null).campo((String)x.get("campo")).valorNum(x.get("valorNum")==null?null:((Number)x.get("valorNum")).doubleValue()).valorTexto((String)x.get("valorTexto")).aferidoEm(LocalDateTime.parse(((String)x.get("aferidoEm")).replace("Z",""))).foraDoPadrao(false).build();return leitura(leituras.save(l));}
 private Map<String,Object> leitura(Leitura r){Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getId());m.put("patientId",r.getPessoa().getId());m.put("measurementTypeId",r.getTipo().getId());m.put("campo",r.getCampo());m.put("valorNum",r.getValorNum());m.put("valorTexto",r.getValorTexto());m.put("aferidoEm",r.getAferidoEm().toString());m.put("foraDoPadrao",r.isForaDoPadrao());m.put("motivoDesvio",r.getMotivoDesvio());return m;}
 @GetMapping("/api/alertas") List<Map<String,Object>> alertas(@RequestParam(required=false) Long patientId,Authentication a){acesso.usuario(a.getName());List<Alerta> l=patientId==null?alertas.findByPessoaUsuarioEmailOrderByCriadoEmDesc(a.getName()):alertas.findByPessoaIdOrderByCriadoEmDesc(acesso.pessoa(patientId,a.getName()).getId());return l.stream().filter(x->x.getReconhecidoEm()==null).map(this::alerta).toList();}
 @PostMapping("/api/alertas") @ResponseStatus(HttpStatus.CREATED) Map<String,Object> criarAlerta(@RequestBody Map<String,Object>x,Authentication a){Pessoa p=acesso.pessoa(((Number)x.get("patientId")).longValue(),a.getName());Long ref=x.get("referenciaId")==null?null:((Number)x.get("referenciaId")).longValue();if(ref!=null){for(Alerta old:alertas.findByPessoaIdOrderByCriadoEmDesc(p.getId()))if(old.getReconhecidoEm()==null&&old.getTipo().equals(x.get("tipo"))&&Objects.equals(old.getReferenciaId(),ref))return null;}Alerta z=Alerta.builder().pessoa(p).tipo((String)x.get("tipo")).severidade((String)x.get("severidade")).titulo((String)x.get("titulo")).detalhe((String)x.get("detalhe")).referenciaId(ref).criadoEm(LocalDateTime.now()).build();return alerta(alertas.save(z));}
 @DeleteMapping("/api/alertas/referencia/{tipo}/{ref}") void resolverAlerta(@PathVariable String tipo,@PathVariable Long ref,@RequestParam(required=false) Long patientId,Authentication a){acesso.usuario(a.getName());List<Alerta> l=patientId==null?alertas.findByPessoaUsuarioEmailOrderByCriadoEmDesc(a.getName()):alertas.findByPessoaIdOrderByCriadoEmDesc(acesso.pessoa(patientId,a.getName()).getId());l.stream().filter(x->x.getReconhecidoEm()==null&&x.getTipo().equals(tipo)&&Objects.equals(x.getReferenciaId(),ref)).forEach(x->{x.setReconhecidoEm(LocalDateTime.now());alertas.save(x);});}
 @PatchMapping("/api/alertas/{id}/reconhecer") void reconhecer(@PathVariable Long id,Authentication a){Alerta x=alertas.findById(id).orElseThrow();acesso.pessoa(x.getPessoa().getId(),a.getName());x.setReconhecidoEm(LocalDateTime.now());x.setReconhecidoPor(acesso.usuario(a.getName()));alertas.save(x);}
 @PutMapping("/api/notas/{id}") Map<String,Object> editarNota(@PathVariable Long id,@RequestBody Map<String,Object>x,Authentication a){Nota n=notas.findById(id).orElseThrow();acesso.pessoa(n.getPessoa().getId(),a.getName());if(x.get("titulo")!=null)n.setTitulo((String)x.get("titulo"));if(x.get("quando")!=null)n.setQuando(LocalDateTime.parse((String)x.get("quando")));if(x.get("texto")!=null)n.setTexto((String)x.get("texto"));return nota(notas.save(n));}
 @PatchMapping("/api/notas/{id}/pulado") Map<String,Object> pularNota(@PathVariable Long id,@RequestBody Map<String,Object>x,Authentication a){Nota n=notas.findById(id).orElseThrow();acesso.pessoa(n.getPessoa().getId(),a.getName());n.setStatus("pulado");n.setMotivoPulo((String)x.get("motivo"));return nota(notas.save(n));}
 @GetMapping("/api/pessoas/{id}/compartilhamento") Map<String,Object> ativo(@PathVariable Long id,Authentication a){Pessoa p=acesso.pessoa(id,a.getName());return compartilhamentos.findFirstByPessoaIdAndRevogadoFalseAndExpiraEmAfter(id,LocalDateTime.now()).map(this::share).orElse(null);}
 @PostMapping("/api/pessoas/{id}/compartilhamento") Map<String,Object> compartilhar(@PathVariable Long id,Authentication a){Pessoa p=acesso.pessoa(id,a.getName());compartilhamentos.findAll().stream().filter(x->x.getPessoa().getId().equals(id)&&!x.isRevogado()).forEach(x->{x.setRevogado(true);compartilhamentos.save(x);});Compartilhamento x=Compartilhamento.builder().token(UUID.randomUUID().toString().replace("-","")).pessoa(p).criadoPor(acesso.usuario(a.getName())).criadoEm(LocalDateTime.now()).expiraEm(LocalDateTime.now().plusDays(7)).revogado(false).build();return share(compartilhamentos.save(x));}
 @DeleteMapping("/api/compartilhamentos/{token}") void revogar(@PathVariable String token,Authentication a){Compartilhamento x=compartilhamentos.findById(token).orElseThrow();acesso.pessoa(x.getPessoa().getId(),a.getName());x.setRevogado(true);compartilhamentos.save(x);}
 @GetMapping("/public/compartilhamentos/{token}") Map<String,Object> resolverPublico(@PathVariable String token){Compartilhamento x=compartilhamentos.findById(token).orElse(null);if(x==null||x.isRevogado()||x.getExpiraEm().isBefore(LocalDateTime.now()))return null;x.setUltimoAcessoEm(LocalDateTime.now());compartilhamentos.save(x);return share(x);}
 private Map<String,Object> share(Compartilhamento x){Map<String,Object>m=new LinkedHashMap<>();m.put("token",x.getToken());m.put("patientId",x.getPessoa().getId());m.put("criadoPor",x.getCriadoPor().getId());m.put("criadoEm",x.getCriadoEm().toString());m.put("expiraEm",x.getExpiraEm().toString());m.put("escopo","dia_atual");m.put("revogado",x.isRevogado());m.put("ultimoAcessoEm",x.getUltimoAcessoEm()==null?null:x.getUltimoAcessoEm().toString());return m;}
}
