import { format } from 'date-fns';
import type { CareEvent, Caregiver, Patient, CareTask, MeasurementType, Reading, Alert, ShareLink } from '$lib/domain/types';
import type { EventService, PatientService, Services, TaskService, MeasurementService, AlertService, ShareService } from './types';

const API_BASE_URL=((typeof import.meta.env.PUBLIC_API_BASE_URL==='string'?import.meta.env.PUBLIC_API_BASE_URL:'').trim().replace(/\/$/,'')||'https://c2ojnf3eqzcxvnnr76mnxzhb5u.apigateway.sa-saopaulo-1.oci.customer-oci.com');
const TOKEN_KEY='cuida-mais:api-token'; const CAREGIVER_KEY='cuida-mais:api-caregiver';
type M=Record<string,any>; const stored=()=>localStorage.getItem(TOKEN_KEY); const clear=()=>{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(CAREGIVER_KEY);};
const parse=(v:any,d:any)=>{try{return v==null?d:typeof v==='string'?JSON.parse(v):v}catch{return d}}; const arr=(v:any)=>Array.isArray(v)?v:parse(v,[]);
async function get<T>(path:string,init:RequestInit={},auth=true):Promise<T>{const h=new Headers(init.headers);if(init.body&&!h.has('Content-Type'))h.set('Content-Type','application/json');const t=auth?stored():null;if(t)h.set('Authorization','Bearer '+t);const r=await fetch(API_BASE_URL+path,{...init,headers:h});if(r.status===401&&auth){clear();throw Error('Sessão expirada. Entre novamente.');}if(!r.ok){let m='API indisponível ('+r.status+')';try{const b=await r.json();m=b.message||b.erro||m}catch{}throw Error(m);}if(r.status===204)return undefined as T;const s=await r.text();return s?JSON.parse(s):undefined as T;}
function jwt(t:string):M{try{const s=t.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(atob(s.padEnd(s.length+(4-s.length%4)%4,'=')))}catch{return {}}}
function cg(t:string,n?:string):Caregiver{const email=String(jwt(t).sub||'cuidador@api.local');return {id:'api:'+email,nome:n||email,email,senhaHash:'',criadoEm:new Date().toISOString()};}
function pat(x:M,c:string):Patient{return {id:String(x.id),caregiverId:c,nome:x.nome,dataNascimento:x.dataNascimento||'1970-01-01',fotoUrl:x.fotoUrl||undefined,localizacao:x.localizacao||undefined,responsavel:x.responsavelNome?{nome:x.responsavelNome,parentesco:x.responsavelParentesco||undefined,telefone:x.responsavelTelefone||undefined}:undefined,alergias:arr(x.alergias),condicoes:arr(x.condicoes),observacoes:x.observacoes||x.identificacao||undefined,ativo:x.ativo!==false,criadoEm:x.criadoEm||new Date(0).toISOString()};}
function task(x:M):CareTask{return {id:String(x.id),patientId:String(x.patientId),tipo:x.tipo,titulo:x.titulo,descricao:x.descricao||undefined,horarios:arr(x.horarios),diasSemana:arr(x.diasSemana).map(Number),toleranciaMin:Number(x.toleranciaMin||30),lembreteAntesMin:Number(x.lembreteAntesMin||15),measurementTypeIds:x.measurementTypeIds?arr(x.measurementTypeIds).map(String):undefined,medicacao:x.medicacao||undefined,ativo:x.ativo!==false};}
function ev(x:M,p:string,c:string):CareEvent{return {id:String(x.id),patientId:p,taskId:x.rotinaId==null?undefined:String(x.rotinaId),tipo:x.tipo||'outro',titulo:x.titulo||'Nota',observacao:x.texto||x.observacao,ocorridoEm:x.quando,registradoEm:x.criadoEm,registradoPor:c,status:x.status||'realizado',motivoPulo:x.motivoPulo,sincronizado:true};}
function rd(x:M):Reading{return {id:String(x.id),patientId:String(x.patientId),eventId:String(x.eventId||''),measurementTypeId:String(x.measurementTypeId),campo:x.campo,aferidoEm:x.aferidoEm,valorNum:x.valorNum,valorTexto:x.valorTexto,foraDoPadrao:Boolean(x.foraDoPadrao),motivoDesvio:x.motivoDesvio,sincronizado:true};}
function mt(x:M):MeasurementType{return {id:String(x.id),slug:x.slug,nome:x.nome,icone:x.icone||'📏',campos:arr(x.campos),alertaSemRegistroHoras:x.alertaSemRegistroHoras,sistema:Boolean(x.sistema),ativo:x.ativo!==false};} function al(x:M):Alert{return {id:String(x.id),patientId:String(x.patientId),tipo:x.tipo,severidade:x.severidade,titulo:x.titulo,detalhe:x.detalhe,referenciaId:x.referenciaId,criadoEm:x.criadoEm,reconhecidoEm:x.reconhecidoEm,reconhecidoPor:x.reconhecidoPor};}
const auth:Services['auth']={async cadastrar({nome,email,senha}){await get('/auth/register',{method:'POST',body:JSON.stringify({nome,tipoCuidador:'independente',email,senha})},false);const c=await auth.login(email,senha);if(!c)throw Error('Não foi possível iniciar a sessão');const s={...c,nome};localStorage.setItem(CAREGIVER_KEY,JSON.stringify(s));return s;},async login(email,senha){const t=await get<string>('/auth/login',{method:'POST',body:JSON.stringify({email,senha})},false);if(typeof t!=='string')return null;const c=cg(t);localStorage.setItem(TOKEN_KEY,t);localStorage.setItem(CAREGIVER_KEY,JSON.stringify(c));return c;},async sessaoAtual(){const t=stored(),r=localStorage.getItem(CAREGIVER_KEY);if(!t||!r)return null;const p=jwt(t);if(typeof p.exp==='number'&&p.exp*1000<=Date.now()){clear();return null;}return JSON.parse(r);},async logout(){clear();}};
const body=(d:any)=>({nome:d.nome,dataNascimento:d.dataNascimento,identificacao:d.observacoes,fotoUrl:d.fotoUrl,localizacao:d.localizacao,responsavelNome:d.responsavel?.nome,responsavelParentesco:d.responsavel?.parentesco,responsavelTelefone:d.responsavel?.telefone,alergias:d.alergias?.join(', '),condicoes:d.condicoes?.join(', '),observacoes:d.observacoes});
const patients:PatientService={async listar(c){return (await get<M[]>('/api/pessoas')).map(x=>pat(x,c));},async obter(id){return pat(await get<M>('/api/pessoas/'+id),(await auth.sessaoAtual())?.id||'api:unknown');},async criar(d){return pat(await get<M>('/api/pessoas',{method:'POST',body:JSON.stringify(body(d))}),d.caregiverId);},async atualizar(id,d){return pat(await get<M>('/api/pessoas/'+id,{method:'PUT',body:JSON.stringify(body(d))}),(await auth.sessaoAtual())?.id||'api:unknown');},async arquivar(id){await get('/api/pessoas/'+id,{method:'DELETE'});}};
const tasks:TaskService={async listarPorPaciente(p,inc=false){return (await get<M[]>('/api/pessoas/'+p+'/rotinas?incluirInativas='+inc)).map(task);},async obter(id){return task(await get('/api/rotinas/'+id));},async criar(d){return task(await get('/api/pessoas/'+d.patientId+'/rotinas',{method:'POST',body:JSON.stringify(d)}));},async atualizar(id,d){return task(await get('/api/rotinas/'+id,{method:'PUT',body:JSON.stringify(d)}));},async alternarAtivo(id,a){await get('/api/rotinas/'+id,{method:'PATCH',body:JSON.stringify({ativo:a})});},async reporEstoque(id,q){return task(await get('/api/rotinas/'+id,{method:'PATCH',body:JSON.stringify({quantidadeAtual:q})}));}};
const events:EventService={async listarPorDia(p,d){const c=await auth.sessaoAtual();const a=await get<M[]>('/api/registros/pessoas/'+p+'/notas');const day=format(d,'yyyy-MM-dd');return a.filter(x=>String(x.quando).startsWith(day)).map(x=>ev(x,p,c?.id||'api:unknown'));},async obter(id){throw Error('Evento '+id+' deve ser obtido pela listagem do paciente');},async criar(d,ls=[]){const n=await get<M>('/api/registros/pessoas/'+d.patientId+'/notas',{method:'POST',body:JSON.stringify({titulo:d.titulo,quando:d.ocorridoEm,texto:d.observacao||d.titulo,rotinaId:d.taskId?Number(d.taskId):undefined,tipo:d.tipo,status:d.status})});for(const l of ls)await get('/api/pessoas/'+d.patientId+'/leituras',{method:'POST',body:JSON.stringify({...l,measurementTypeId:Number(l.measurementTypeId)})});return ev(n,d.patientId,d.registradoPor);},async editar(id,d,reason){const n=await get<M>('/api/notas/'+id,{method:'PUT',body:JSON.stringify({titulo:d.titulo,quando:d.ocorridoEm,texto:d.observacao||d.titulo,motivoEdicao:reason})});return ev(n,String(n.pessoa?.id||d.patientId||''),d.registradoPor||'');},async marcarPulado(id,motivo){const n=await get<M>('/api/notas/'+id+'/pulado',{method:'PATCH',body:JSON.stringify({motivo})});return ev(n,String(n.pessoa?.id||n.pessoaId||''),'');}};
const measurements:MeasurementService={async listarTipos(i=false){return (await get<M[]>('/api/tipos-afericao?incluirInativas='+i)).map(mt);},async obterTipo(id){return mt(await get('/api/tipos-afericao/'+id));},async criarTipo(d){return mt(await get('/api/tipos-afericao',{method:'POST',body:JSON.stringify(d)}));},async atualizarTipo(id,d){return mt(await get('/api/tipos-afericao/'+id,{method:'PUT',body:JSON.stringify(d)}));},async alternarAtivo(id,a){await get('/api/tipos-afericao/'+id,{method:'PATCH',body:JSON.stringify({ativo:a})});},async leituras(p,t,c,l){const a=(await get<M[]>('/api/pessoas/'+p+'/leituras?tipo='+t+'&campo='+encodeURIComponent(c))).map(rd);return l?a.slice(0,l):a;},async ultimaLeituraDoTipo(p,t){return (await get<M[]>('/api/pessoas/'+p+'/leituras?tipo='+t)).map(rd)[0];},async leiturasForaDoPadrao(p){return (await get<M[]>('/api/pessoas/'+p+'/leituras')).filter(x=>x.foraDoPadrao).map(rd);},async camposRegistrados(p){const a=await get<M[]>('/api/pessoas/'+p+'/leituras');return [...new Map(a.map(x=>[x.measurementTypeId+'|'+x.campo,{measurementTypeId:String(x.measurementTypeId),campo:x.campo}])).values()];}};
const alerts:AlertService={async listar(f={}){const q=f.patientId?'?patientId='+f.patientId:'';return (await get<M[]>('/api/alertas'+q)).map(al);},async criarSeNovo(d){const x=await get<M|null>('/api/alertas',{method:'POST',body:JSON.stringify({...d,patientId:Number(d.patientId),referenciaId:d.referenciaId==null?undefined:Number(d.referenciaId)})});return x?al(x):null;},async reconhecer(id){await get('/api/alertas/'+id+'/reconhecer',{method:'PATCH'});},async resolverPorReferencia(tipo,ref,pid){await get('/api/alertas/referencia/'+tipo+'/'+ref+(pid?'?patientId='+pid:''),{method:'DELETE'});}};
const share:ShareService={async gerar(p){return get<ShareLink>('/api/pessoas/'+p+'/compartilhamento',{method:'POST'});},async ativo(p){return (await get<ShareLink|null>('/api/pessoas/'+p+'/compartilhamento'))||undefined;},async revogar(t){await get('/api/compartilhamentos/'+t,{method:'DELETE'});},async resolverToken(t){return (await get<ShareLink|null>('/public/compartilhamentos/'+t,{},false))||null;}};
export const apiServices:Services={async inicializar(){},auth,patients,tasks,events,measurements,alerts,share,demo:{async resetar(){throw Error('Reset disponível somente no perfil local.');}}};
